#import <Foundation/Foundation.h>
#import "SystranTranscriptionSupportedLanguagesResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranTranscriptionApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranTranscriptionApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranTranscriptionApi*) sharedAPI;
///
///
/// Supported Languages
/// List of languages pairs in which Transcription is supported. This list can be limited to a specific source language or target language.
///
/// @param source Source Language code ([details](#description_langage_code_values))
/// @param target Target Language code ([details](#description_langage_code_values))
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranTranscriptionSupportedLanguagesResponse*
-(NSNumber*) nlpTranscriptionSupportedLanguagesGetWithCompletionBlock :(NSString*) source 
     target:(NSString*) target 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranTranscriptionSupportedLanguagesResponse* output, NSError* error))completionBlock;
    


///
///
/// Transcribe
/// Transcribe text from a source language to a target language.
///
/// @param source Source Language code ([details](#description_langage_code_values))
/// @param target Target Language code ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return NSURL*
-(NSNumber*) nlpTranscriptionTranscribePostWithCompletionBlock :(NSString*) source 
     target:(NSString*) target 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(NSURL* output, NSError* error))completionBlock;
    



@end
