#import <Foundation/Foundation.h>
#import "SystranSegmentationSegmentResponse.h"
#import "SystranSegmentationSegmentAndTokenizeResponse.h"
#import "SystranSupportedLanguagesResponse.h"
#import "SystranSegmentationTokenizeResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranSegmentationApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranSegmentationApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranSegmentationApi*) sharedAPI;
///
///
/// Segment
/// Segment an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSegmentationSegmentResponse*
-(NSNumber*) nlpSegmentationSegmentPostWithCompletionBlock :(NSString*) lang 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranSegmentationSegmentResponse* output, NSError* error))completionBlock;
    


///
///
/// Segment and tokenize
/// Segment an input text, then tokenize each segment.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSegmentationSegmentAndTokenizeResponse*
-(NSNumber*) nlpSegmentationSegmentAndTokenizePostWithCompletionBlock :(NSString*) lang 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranSegmentationSegmentAndTokenizeResponse* output, NSError* error))completionBlock;
    


///
///
/// Supported Languages
/// List of languages in which Segmentation is supported.
///
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSupportedLanguagesResponse*
-(NSNumber*) nlpSegmentationSupportedLanguagesGetWithCompletionBlock :(NSString*) callback 
    
    completionHandler: (void (^)(SystranSupportedLanguagesResponse* output, NSError* error))completionBlock;
    


///
///
/// Tokenize
/// Tokenize an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSegmentationTokenizeResponse*
-(NSNumber*) nlpSegmentationTokenizePostWithCompletionBlock :(NSString*) lang 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranSegmentationTokenizeResponse* output, NSError* error))completionBlock;
    



@end
