#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranNerEntityAnnotation
@end

@interface SystranNerEntityAnnotation : SystranObject

/* Start offset 
 */
@property(nonatomic) NSNumber* start;
/* End offset 
 */
@property(nonatomic) NSNumber* end;
/* Entity type 
 */
@property(nonatomic) NSString* type;

@end
