#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranPosAnnotation
@end

@interface SystranPosAnnotation : SystranObject

/* Text 
 */
@property(nonatomic) NSString* text;
/* Part of speech 
 */
@property(nonatomic) NSString* pos;
/* Start offset 
 */
@property(nonatomic) NSNumber* start;
/* End offset 
 */
@property(nonatomic) NSNumber* end;

@end
