#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranLidParagraph.h"
#import "SystranErrorResponse.h"


@protocol SystranLidParagraphResponse
@end

@interface SystranLidParagraphResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of paragraphs [optional]
 */
@property(nonatomic) NSArray<SystranLidParagraph>* paragraphs;

@end
