#import <Foundation/Foundation.h>
#import "SystranMorphologyExtractLemmaResponse.h"
#import "SystranMorphologyExtractNPResponse.h"
#import "SystranMorphologyExtractPosResponse.h"
#import "SystranSupportedLanguagesResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranMorphologyApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranMorphologyApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranMorphologyApi*) sharedAPI;
///
///
/// Get lemma
/// Get the lemma for elements of an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranMorphologyExtractLemmaResponse*
-(NSNumber*) nlpMorphologyExtractLemmaPostWithCompletionBlock :(NSString*) lang 
     input:(NSString*) input 
     inputFile:(NSURL*) inputFile 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranMorphologyExtractLemmaResponse* output, NSError* error))completionBlock;
    


///
///
/// Get NP/chunks
/// Get Noun-phrases and chunks from an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranMorphologyExtractNPResponse*
-(NSNumber*) nlpMorphologyExtractNpPostWithCompletionBlock :(NSString*) lang 
     input:(NSString*) input 
     inputFile:(NSURL*) inputFile 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranMorphologyExtractNPResponse* output, NSError* error))completionBlock;
    


///
///
/// Get part of speech
/// Get the part of speech for elements of an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranMorphologyExtractPosResponse*
-(NSNumber*) nlpMorphologyExtractPosPostWithCompletionBlock :(NSString*) lang 
     input:(NSString*) input 
     inputFile:(NSURL*) inputFile 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(NSString* output, NSError* error))completionBlock;
    


///
///
/// Supported Languages
/// List of languages pairs in which Morphological analysis is supported.
///
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSupportedLanguagesResponse*
-(NSNumber*) nlpMorphologySupportedLanguagesGetWithCompletionBlock :(NSString*) callback 
    
    completionHandler: (void (^)(SystranSupportedLanguagesResponse* output, NSError* error))completionBlock;
    



@end
