#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranPosAnnotation.h"
#import "SystranErrorResponse.h"


@protocol SystranMorphologyExtractPosResponse
@end

@interface SystranMorphologyExtractPosResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Part of speech per text elements 
 */

@property(nonatomic) NSArray<SystranPosAnnotation>* partsOfSpeech;

@end
