#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranLidDetectedLanguage.h"


@protocol SystranLidParagraph
@end

@interface SystranLidParagraph : SystranObject

/* Array of detected languages 
 */
@property(nonatomic) NSArray<SystranLidDetectedLanguage>* detectedLanguages;
/* Paragraph text 
 */
@property(nonatomic) NSString* source;

@end
