#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranNerEntity.h"
#import "SystranErrorResponse.h"


@protocol SystranNerExtractEntitiesResponse
@end

@interface SystranNerExtractEntitiesResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of found entities 
 */
@property(nonatomic) NSArray<SystranNerEntity>* entities;

@end
