#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranErrorResponse.h"
#import "SystranChunkAnnotation.h"


@protocol SystranMorphologyExtractNPResponse
@end

@interface SystranMorphologyExtractNPResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* List of extracted chunks 
 */
@property(nonatomic) NSArray<SystranChunkAnnotation>* chunks;

@end
