#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSegmentationToken.h"
#import "SystranErrorResponse.h"


@protocol SystranSegmentationTokenizeResponse
@end

@interface SystranSegmentationTokenizeResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of tokens 
 */
@property(nonatomic) NSArray<SystranSegmentationToken>* tokens;

@end
