#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranProfile.h"


@protocol SystranSupportedLanguage
@end

@interface SystranSupportedLanguage : SystranObject

/* Language code 
 */
@property(nonatomic) NSString* lang;
/* Array of profiles 
 */
@property(nonatomic) NSArray<SystranProfile>* profiles;

@end
