#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSegmentationTokenizedSegment.h"
#import "SystranErrorResponse.h"


@protocol SystranSegmentationSegmentAndTokenizeResponse
@end

@interface SystranSegmentationSegmentAndTokenizeResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of segments 
 */
@property(nonatomic) NSArray<SystranSegmentationTokenizedSegment>* segments;

@end
