#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranNerEntity
@end

@interface SystranNerEntity : SystranObject

/* Type 
 */
@property(nonatomic) NSString* type;
/* Value 
 */
@property(nonatomic) NSString* value;

@end
