#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranNerEntityAnnotation.h"


@protocol SystranNerSegmentAnnotation
@end

@interface SystranNerSegmentAnnotation : SystranObject

/* Text segment 
 */
@property(nonatomic) NSString* source;
/* Array of found entities 
 */
@property(nonatomic) NSArray<SystranNerEntityAnnotation>* entities;

@end
