#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranProfile.h"


@protocol SystranSupportedLanguagePair
@end

@interface SystranSupportedLanguagePair : SystranObject

/* Source language code 
 */
@property(nonatomic) NSString* source;
/* Target language code 
 */
@property(nonatomic) NSString* target;
/* Array of profiles 
 */
@property(nonatomic) NSArray<SystranProfile>* profiles;

@end
