#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranSegmentationToken
@end

@interface SystranSegmentationToken : SystranObject

/* Token text 
 */
@property(nonatomic) NSString* source;
/* Token type 
 */
@property(nonatomic) NSString* type;

@end
