#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranLemmaAnnotation
@end

@interface SystranLemmaAnnotation : SystranObject

/* Text 
 */
@property(nonatomic) NSString* text;
/* Lemma 
 */
@property(nonatomic) NSString* lemma;
/* Start offset 
 */
@property(nonatomic) NSNumber* start;
/* End offset 
 */
@property(nonatomic) NSNumber* end;

@end
