#import <Foundation/Foundation.h>
#import "SystranNerExtractAnnotationsResponse.h"
#import "SystranNerExtractEntitiesResponse.h"
#import "SystranSupportedLanguagesResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranNerApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranNerApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranNerApi*) sharedAPI;
///
///
/// Get entity annotations
/// Get the list of entity annotations given an input text.\nAn entity annotation is an entity associated with its position in the text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranNerExtractAnnotationsResponse*
-(NSNumber*) nlpNerExtractAnnotationsPostWithCompletionBlock :(NSString*) lang 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranNerExtractAnnotationsResponse* output, NSError* error))completionBlock;
    


///
///
/// Get list of entities
/// Get the list of different entities given an input text.
///
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param inputFile input text\n\n**Either `input` or `inputFile` is required**
/// @param input input text\n\n**Either `input` or `inputFile` is required**
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranNerExtractEntitiesResponse*
-(NSNumber*) nlpNerExtractEntitiesPostWithCompletionBlock :(NSString*) lang 
     inputFile:(NSURL*) inputFile 
     input:(NSString*) input 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranNerExtractEntitiesResponse* output, NSError* error))completionBlock;
    


///
///
/// Supported Languages
/// List of languages in which NER is supported.
///
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSupportedLanguagesResponse*
-(NSNumber*) nlpNerSupportedLanguagesGetWithCompletionBlock :(NSString*) callback 
    
    completionHandler: (void (^)(SystranSupportedLanguagesResponse* output, NSError* error))completionBlock;
    



@end
