#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranLidDetectedLanguage
@end

@interface SystranLidDetectedLanguage : SystranObject

/* Language 
 */
@property(nonatomic) NSString* lang;
/* Confidence 
 */
@property(nonatomic) NSNumber* confidence;

@end
