#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranProfile
@end

@interface SystranProfile : SystranObject

/* Profile identifier 
 */
@property(nonatomic) NSString* _id;
/* Public or private profile 
 */
@property(nonatomic) NSString* private;

@end
