#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSegmentationToken.h"


@protocol SystranSegmentationTokenizedSegment
@end

@interface SystranSegmentationTokenizedSegment : SystranObject

/* Segment 
 */
@property(nonatomic) NSString* source;
/* Array of tokens 
 */
@property(nonatomic) NSArray<SystranSegmentationToken>* tokens;

@end
